### ISSUE TITLE
Notification doesn't collapse

### ISSUE THREAD

**Issue by saulmm** [googlesamples/android-CustomNotifications#1]
When I run the sample on my device and try to swipe up to collapse the notification, the whole notification panel its collapsed instead the notification itself.

![](https://dl.pushbulletusercontent.com/dH9AEktAETxjSpbMAcG4EZZU2PLPzqxS/hammerheadLMY48Msaulmm10022015114020.png)

**Comment by keyboardsurfer** [comment]
In order to collapse the notification you need to swipe up with two fingers.
If this issue persists, please re-open with more information on the device and Android version.
